# Generated by Django 5.2.5 on 2025-08-26 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('card', '신용카드'), ('bank', '무통장입금'), ('kakao', '카카오페이')], max_length=20, verbose_name='결제방법')),
                ('status', models.CharField(choices=[('pending', '결제대기'), ('completed', '결제완료'), ('failed', '결제실패'), ('cancelled', '결제취소'), ('refunded', '환불완료')], default='pending', max_length=20, verbose_name='결제상태')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='결제금액')),
                ('currency', models.CharField(default='KRW', max_length=3, verbose_name='통화')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='거래번호')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='환불금액')),
                ('reason', models.TextField(verbose_name='환불사유')),
                ('status', models.CharField(choices=[('requested', '환불요청'), ('processing', '환불처리중'), ('completed', '환불완료'), ('rejected', '환불거절')], default='requested', max_length=20, verbose_name='환불상태')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Refund ID')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('admin_memo', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='결제')),
            ],
            options={
                'verbose_name': '환불',
                'verbose_name_plural': '환불',
            },
        ),
    ]
