# Generated by Django 5.2.5 on 2025-09-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='기본 배송 주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_phone',
            field=models.CharField(blank=True, help_text='기본 배송지 연락처', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_zipcode',
            field=models.CharField(blank=True, help_text='기본 배송지 우편번호', max_length=10),
        ),
    ]
