# Generated by Django 5.2.5 on 2025-09-16 04:44

import accounts.models
import shopping_mall.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_shipping_address_user_shipping_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eye_exam_file',
            field=models.FileField(blank=True, help_text='시력 검사 결과 파일 (PDF, 이미지 등)', null=True, storage=shopping_mall.storage_backends.UserFileStorage(), upload_to=accounts.models.user_eye_exam_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='eye_exam_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='시력 검사 파일 업로드 시간', null=True),
        ),
    ]
