# Generated by Django 5.2.5 on 2025-09-16 04:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_eye_exam_file_user_eye_exam_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eye_exam_file',
            field=models.FileField(blank=True, help_text='시력 검사 결과 파일 (PDF, 이미지 등)', null=True, upload_to=accounts.models.user_eye_exam_upload_path),
        ),
    ]
