# Generated by Django 5.2.5 on 2025-09-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_eye_exam_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shipping_city',
            field=models.CharField(blank=True, help_text='도시', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_country',
            field=models.CharField(blank=True, help_text='국가', max_length=100),
        ),
    ]
