# Generated by Django 5.2.5 on 2025-09-16 05:10

import celebrities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Celebrity Name')),
                ('description', models.TextField(blank=True, help_text='Description about the celebrity or look')),
                ('image', models.ImageField(storage=celebrities.models.CelebrityImageStorage(), upload_to=celebrities.models.celebrity_image_path, verbose_name='Celebrity Photo')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this celebrity photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Celebrity Look',
                'verbose_name_plural': 'Celebrity Looks',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
