# Generated by Django 5.2.5 on 2025-08-26 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('confirmed', '주문확인'), ('preparing', '상품준비중'), ('shipped', '배송중'), ('delivered', '배송완료'), ('cancelled', '주문취소')], default='pending', max_length=20, verbose_name='주문상태')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='배송받는 분')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='배송주소')),
                ('shipping_detail_address', models.CharField(blank=True, max_length=255, verbose_name='상세주소')),
                ('shipping_zipcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 주문금액')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='배송비')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='할인금액')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='최종 결제금액')),
                ('memo', models.TextField(blank=True, verbose_name='배송 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='상품가격')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '장바구니 상품',
                'verbose_name_plural': '장바구니 상품',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
