# Generated by Django 5.2.5 on 2025-09-07 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, default='온라인 주문', max_length=255, null=True, verbose_name='배송주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, default='온라인 주문자', max_length=100, null=True, verbose_name='배송받는 분'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, default='미제공', max_length=20, null=True, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zipcode',
            field=models.CharField(blank=True, default='00000', max_length=10, null=True, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문자'),
        ),
    ]
