# Generated by Django 5.2.5 on 2025-09-09 01:41

import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to=products.utils.UUIDFileNameGenerator('brands'), verbose_name='브랜드 로고'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.utils.UUIDFileNameGenerator('products'), verbose_name='상품 이미지'),
        ),
    ]
