# Generated by Django 5.2.5 on 2025-09-09 04:52

import django.db.models.deletion
import products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_logo_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.utils.UUIDFileNameGenerator('model_photos'), verbose_name='착용사진')),
                ('caption', models.CharField(max_length=200, verbose_name='사진 설명')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='대체 텍스트')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_photos', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '착용사진',
                'verbose_name_plural': '착용사진',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
