# Generated by Django 5.2.5 on 2025-09-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_modelphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공지사항 제목')),
                ('content', models.TextField(verbose_name='공지사항 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_banner', models.BooleanField(default=False, verbose_name='상단 배너 표시')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
